//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: System.Reflection.AssemblyProduct("Xps2PdfConverter")]
[assembly: System.Reflection.AssemblyCopyright("Copyright © 2017. All rights reserved.")]
[assembly: System.Reflection.AssemblyVersion("1.2017.0712")]
[assembly: System.Reflection.AssemblyFileVersion("1.2017.0712")]
[assembly: System.Reflection.AssemblyInformationalVersion("1.2017.0712.7a26c10")]



internal sealed partial class ThisAssembly {
    
    internal const string AssemblyProduct = "Xps2PdfConverter";
    
    internal const string AssemblyCopyright = "Copyright © 2017. All rights reserved.";
    
    internal const string AssemblyVersion = "1.2017.0712";
    
    internal const string AssemblyFileVersion = "1.2017.0712";
    
    internal const string AssemblyInformationalVersion = "1.2017.0712.7a26c10";
    
    private ThisAssembly() {
    }
}
